version: '3.8'

services:
  # Spring Boot application service
  app:
    image: giorgospls/matchoddsmanager
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: test123
    depends_on:
      - postgres
    restart: always

  # PostgreSQL database service
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

# Named volume for persisting PostgreSQL data
volumes:
  postgres-data:
